#pragma once

#include "xstd/xstd_coretypes.h"
#include "xstd/xstd_err.h"
#include "xstd/xstd_result.h"
#include "xstd/xstd_alloc.h"
#include "xstd/xstd_alloc_c.h"
#include "xstd/xstd_buffer.h"
#include "xstd/xstd_list.h"
#include "xstd/xstd_str.h"
#include "xstd/xstd_file_os_int.h"
#include "xstd/xstd_file_os_int_c.h"
#include "xstd/xstd_file.h"
#include "xstd/xstd_io.h"
#include "xstd/xstd_alloc_arena.h"
#include "xstd/xstd_alloc_debug.h"
